kafka:
  broker: "localhost:39092,localhost:39093,localhost:39094"
  topic: "customer_click_data_topic"
flink:
  kafka_broker: "kafka1:19092,kafka2:19093,kafka3:19094"
  consume_topic: "customer_click_data_topic"
  produce_topic: "processed_customer_topic"
  aggregation_window: 30
csv_files:
  - "C:\\Users\\arghy\\Downloads\\532_dataset\\2019_oct.csv"
  - "C:\\Users\\arghy\\Downloads\\532_dataset\\2019_nov.csv"
streaming:
  delay: 1  # Seconds between messages
llm:
  url: http://localhost:5000/
  topic: "processed_customer_topic"